export const MISSION_008 = {
  id: "M08",
  caseNumber: "ACC-008",
  title: "OPERATION BLACKOUT – PART III",
  shortTitle: "MISSION 008",
  subtitle: "THE PAYLOAD",
  category: "Malware Analysis & Incident Containment",
  difficulty: "Advanced",
  points: 100,
  timeLimitSec: 90 * 60,
  startLabel: "ENTER CONTAINMENT MODE",
  series: {
    name: "Operation Blackout",
    part: 3,
    of: 5,
  },
  caseFile: {
    heading: "EMERGENCY UPDATE",
    intro:
      "CLASSIFICATION: TOP SECRET. The threat actor has escaped. However… A suspicious executable has been discovered on multiple university computers. Systems are beginning to slow down. Several files have been renamed. The malware is spreading. Your team has one objective: Investigate. Contain. Protect the network.",
  },
  objectives: [
    "Investigate the suspicious files",
    "Analyze malware behaviour",
    "Identify affected systems",
    "Contain the incident",
    "Recover all hidden flags",
  ],
  evidence: [
    {
      id: "E001",
      title: "Recovered File",
      type: "files",
      description: "Safe file explorer of artefacts recovered from LAB-PC-05.",
    },
    {
      id: "E002",
      title: "Behaviour Report",
      type: "behavior",
      description: "Sandbox observations — no real malware executed.",
    },
    {
      id: "E003",
      title: "Affected Computers",
      type: "systems",
      description: "Campus host health during payload spread.",
    },
    {
      id: "E004",
      title: "Antivirus Scan Report",
      type: "av",
      description: "Enterprise AV detections from the containment window.",
    },
    {
      id: "E005",
      title: "Recovery Plan",
      type: "recovery",
      description: "ACRT checklist for isolating and restoring services.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "Suspicious file flag",
      correct: "BLACKOUT{payload_found}",
      points: 20,
      hint: "Open every recovered artefact. Only the unexpected executable carries the payload token.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "Behaviour analysis flag",
      correct: "BLACKOUT{behavior_analysis}",
      points: 20,
      hint: "Read each sandbox behaviour line — one observation embeds the analysis token.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "Containment ready flag",
      correct: "BLACKOUT{containment_ready}",
      points: 20,
      hint: "Mark every infected host correctly. Completing the board unlocks the containment token.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "Scan complete flag",
      correct: "BLACKOUT{scan_complete}",
      points: 20,
      hint: "Inspect each AV detection card — one threat entry includes the scan token.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "Incident control flag",
      correct: "BLACKOUT{incident_control}",
      points: 20,
      hint: "Work through the recovery checklist. One step contains the control token.",
      evidenceId: "E005",
    },
    {
      id: "F6",
      task: 6,
      label: "Payload contained flag",
      correct: "BLACKOUT{payload_contained}",
      points: 20,
      hint: "Name update.exe, list infected hosts to isolate, and describe immediate recovery actions.",
      requires: ["F1", "F2", "F3", "F4", "F5"],
    },
  ],
  finalReport: {
    fileKeywords: ["update.exe", "update", "executable", "exe", "payload"],
    isolateKeywords: [
      "lab-pc-04",
      "lab pc 04",
      "lab-pc-05",
      "server-03",
      "library-pc",
      "isolate",
      "disconnect",
      "quarantine",
      "infected",
      "contain",
    ],
    actionKeywords: [
      "disconnect",
      "isolate",
      "preserve",
      "evidence",
      "credential",
      "reset",
      "password",
      "quarantine",
      "block",
      "c2",
      "monitor",
      "segment",
      "notify",
    ],
    recoverKeywords: [
      "backup",
      "restore",
      "reimage",
      "clean",
      "verify",
      "monitor",
      "patch",
      "credential",
      "password",
      "snapshot",
      "from backup",
      "safe",
    ],
  },
  skills: [
    "How malware behaves",
    "How to recognize suspicious files",
    "Why containment is critical",
    "How antivirus reports assist investigations",
    "The first steps of malware incident response",
  ],
  badge: "Malware Response Specialist I",
  maxHints: 6,
  hintPenalty: 5,
  bonusNoHints: 10,
  bonusFastMinutes: 75,
  bonusFastPoints: 10,
};
