export const MISSION_009 = {
  id: "M09",
  caseNumber: "ACC-009",
  title: "OPERATION BLACKOUT – FINAL",
  shortTitle: "MISSION 009",
  subtitle: "CYBER CHAMPION",
  category: "Capstone Challenge",
  difficulty: "Expert",
  points: 150,
  timeLimitSec: 120 * 60,
  startLabel: "BEGIN FINAL OPERATION",
  series: {
    name: "Operation Blackout",
    part: 4,
    of: 4,
  },
  caseFile: {
    heading: "FINAL TRANSMISSION",
    intro:
      "CLASSIFICATION: MISSION CRITICAL. After days of investigation… The attack has been traced. The malware has been contained. The compromised systems have been isolated. However… One encrypted archive remains. Inside it lies the attacker's final message and the last pieces of evidence needed to close the case forever. This is your final operation. Recover every piece of evidence. Complete the final report. Secure the university. Earn your place as an ADABAH Cyber Champion.",
  },
  objectives: [
    "Solve the final investigation",
    "Connect evidence from previous missions",
    "Recover every hidden flag",
    "Complete the final incident report",
    "Secure the university",
  ],
  evidence: [
    {
      id: "E001",
      title: "Recovered Archive",
      type: "archive",
      description: "Decrypted contents of the attacker’s leftover archive.",
    },
    {
      id: "E002",
      title: "Communication Log",
      type: "comms",
      description: "Intercepted chatter between threat actors.",
    },
    {
      id: "E003",
      title: "Network Evidence",
      type: "network",
      description: "Final timeline of campus network activity during Blackout.",
    },
    {
      id: "E004",
      title: "Recovered Credentials",
      type: "identity",
      description: "Authentication history used to confirm account takeover.",
    },
    {
      id: "E005",
      title: "Digital Evidence Board",
      type: "board",
      description: "Connect clues from every prior mission into one picture.",
    },
    {
      id: "E006",
      title: "Incident Recovery Checklist",
      type: "checklist",
      description: "Verify that every recovery step is complete.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "Archive flag",
      correct: "BLACKOUT{archive_opened}",
      points: 20,
      hint: "Open every document in the recovered archive — one note holds the token.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "Communication flag",
      correct: "BLACKOUT{final_trace}",
      points: 20,
      hint: "Read the attacker chat to the end. The last operational message embeds the trace.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "Network flag",
      correct: "BLACKOUT{network_secured}",
      points: 20,
      hint: "Inspect each timeline event. One secured segment carries the network token.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "Identity flag",
      correct: "BLACKOUT{identity_recovered}",
      points: 20,
      hint: "Compare login histories — the compromised account reveals the identity token.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "Investigation flag",
      correct: "BLACKOUT{master_investigator}",
      points: 20,
      hint: "Link related clues on the evidence board. Completing the chain unlocks the master token.",
      evidenceId: "E005",
    },
    {
      id: "F6",
      task: 6,
      label: "Recovery flag",
      correct: "BLACKOUT{operation_complete}",
      points: 20,
      hint: "Tick through the recovery checklist. The final verified step holds the operation token.",
      evidenceId: "E006",
    },
    {
      id: "F7",
      task: 7,
      label: "Cyber Champion flag",
      correct: "BLACKOUT{cyber_champion}",
      points: 30,
      hint: "Answer all five report questions using knowledge from Missions 001–008.",
      requires: ["F1", "F2", "F3", "F4", "F5", "F6"],
    },
  ],
  finalReport: {
    beginKeywords: [
      "phish",
      "weak password",
      "password",
      "login",
      "07:39",
      "auth",
      "breach",
      "remote",
      "social",
      "credential",
      "spray",
    ],
    firstSystemKeywords: [
      "lab-pc-05",
      "lab pc 05",
      "auth",
      "authentication",
      "database",
      "utc-db",
      "sso",
    ],
    evidenceKeywords: [
      "ioc",
      "185.243",
      "c2",
      "update.exe",
      "beacon",
      "j.mensah",
      "log",
      "firewall",
      "hash",
      "timeline",
    ],
    stopKeywords: [
      "isolat",
      "contain",
      "quarantine",
      "disconnect",
      "backup",
      "restore",
      "reset",
      "credential",
      "block",
      "monitor",
    ],
    lessonKeywords: [
      "mfa",
      "2fa",
      "password",
      "policy",
      "monitor",
      "backup",
      "train",
      "educat",
      "patch",
      "segment",
      "log",
      "awareness",
      "least privilege",
      "review",
    ],
  },
  skills: [
    "Digital Investigation",
    "Cyber Awareness",
    "Network Security",
    "Authentication",
    "Web Security",
    "Incident Response",
    "Threat Hunting",
    "Malware Analysis",
  ],
  badge: "ADABAH Cyber Champion",
  maxHints: 7,
  hintPenalty: 5,
  bonusNoHints: 15,
  bonusFastMinutes: 90,
  bonusFastPoints: 15,
};
