export const MISSION_002 = {
  id: "M02",
  caseNumber: "ACC-002",
  title: "THE HIDDEN TRAIL",
  shortTitle: "MISSION 002",
  category: "Digital Forensics & OSINT",
  difficulty: "Beginner → Intermediate",
  points: 100,
  timeLimitSec: 60 * 60,
  caseFile: {
    heading: "CASE FILE ACC-002",
    intro:
      "A former UMaT student suddenly disappeared after posting several strange messages online. Investigators managed to recover a few digital files before everything was deleted. Your task is to examine every piece of evidence, discover every hidden clue, and reconstruct exactly what happened. Remember: \"Sometimes the smallest clue solves the biggest mystery.\"",
  },
  objectives: [
    "Examine digital evidence",
    "Discover hidden clues",
    "Connect pieces of evidence",
    "Recover all hidden flags",
    "Reconstruct the final timeline",
  ],
  evidence: [
    {
      id: "E001",
      file: "campus_photo.jpg",
      title: "campus_photo.jpg",
      type: "image",
      description: "Recovered from the student's phone.",
    },
    {
      id: "E002",
      file: "farewell_letter.pdf",
      title: "farewell_letter.pdf",
      type: "pdf",
      description: "Recovered from the student's Downloads folder.",
    },
    {
      id: "E003",
      file: "student_notes.docx",
      title: "student_notes.docx",
      type: "docx",
      description: "Recovered from Documents.",
    },
    {
      id: "E004",
      file: "social_profile",
      title: "Recovered Social Media Profile",
      type: "social",
      description: "Snapshot of the student's last public activity.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "Image metadata flag",
      correct: "ACC{metadata_master}",
      points: 20,
      hint: "Open the photo and inspect its metadata panel — photographers leave traces.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "Hidden PDF message",
      correct: "ACC{hidden_pdf}",
      points: 20,
      hint: "Try selecting the blank-looking areas or check page two carefully.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "Document properties flag",
      correct: "ACC{forensic_eye}",
      points: 20,
      hint: "Document properties can hide more than authors admit — open Properties.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "Social media flag",
      correct: "ACC{social_detective}",
      points: 20,
      hint: "Read every post and comment — someone left a strange reply.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "Timeline completion flag",
      correct: "ACC{case_closed}",
      points: 20,
      hint: "Order the events from first digital action to disappearance.",
      requires: ["F1", "F2", "F3", "F4"],
    },
  ],
  timeline: [
    { id: "t1", label: "Student uploaded photo" },
    { id: "t2", label: "Student received mysterious message" },
    { id: "t3", label: "Student deleted account" },
    { id: "t4", label: "Student disappeared" },
  ],
  timelineCorrect: ["t1", "t2", "t3", "t4"],
  skills: [
    "Digital files contain hidden metadata.",
    "PDFs can hide invisible information.",
    "Document properties reveal valuable evidence.",
    "Social media can expose important intelligence.",
    "Digital investigations rely on observation, patience and connecting clues.",
  ],
  badge: "Digital Investigator I",
  maxHints: 5,
  hintPenalty: 5,
  bonusNoHints: 10,
  bonusFastMinutes: 40,
  bonusFastPoints: 10,
};
