export const MISSION_007 = {
  id: "M07",
  caseNumber: "ACC-007",
  title: "OPERATION BLACKOUT – PART II",
  shortTitle: "MISSION 007",
  subtitle: "THE HUNT",
  category: "Threat Hunting & Log Analysis",
  difficulty: "Advanced",
  points: 100,
  timeLimitSec: 90 * 60,
  startLabel: "BEGIN THREAT HUNT",
  series: {
    name: "Operation Blackout",
    part: 2,
    of: 5,
  },
  caseFile: {
    heading: "PRIORITY UPDATE",
    intro:
      "CLASSIFICATION: TOP SECRET. The breach has been confirmed. Security cameras show no physical intrusion. The attacker is operating remotely. Every minute counts. Your objective is to trace the attacker's movements, identify their methods, and locate the compromised machine before they erase every trace.",
  },
  objectives: [
    "Hunt the attacker",
    "Analyze network activity",
    "Trace suspicious behaviour",
    "Recover hidden intelligence",
    "Identify the compromised system",
  ],
  evidence: [
    {
      id: "E001",
      title: "Network Traffic",
      type: "traffic",
      description: "Live session table — source, destination, protocol, and status.",
    },
    {
      id: "E002",
      title: "Firewall Logs",
      type: "firewall",
      description: "Allowed and blocked flows across the campus edge.",
    },
    {
      id: "E003",
      title: "Endpoint Activity",
      type: "endpoints",
      description: "Process and connection signals from lab and admin hosts.",
    },
    {
      id: "E004",
      title: "User Activity Timeline",
      type: "users",
      description: "Login history across staff accounts during the blackout window.",
    },
    {
      id: "E005",
      title: "Threat Intelligence Report",
      type: "intel",
      description: "IOC packet correlating domains, IPs, and file hashes.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "Network traffic flag",
      correct: "BLACKOUT{network_trail}",
      points: 20,
      hint: "Sort or scan for unusual destinations — one outbound session carries the trail token.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "Firewall log flag",
      correct: "BLACKOUT{firewall_watch}",
      points: 20,
      hint: "Read ALLOW and DENY lines carefully. One rule annotation embeds the watch token.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "Infected host flag",
      correct: "BLACKOUT{infected_host}",
      points: 20,
      hint: "Compare endpoint behaviour. The host with unusual processes reveals the infection marker.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "User trace flag",
      correct: "BLACKOUT{user_trace}",
      points: 20,
      hint: "Look for impossible travel or odd login hours — that account timeline holds the flag.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "IOC flag",
      correct: "BLACKOUT{ioc_found}",
      points: 20,
      hint: "Open every IOC in the threat intel report. One indicator contains the recovery token.",
      evidenceId: "E005",
    },
    {
      id: "F6",
      task: 6,
      label: "Threat contained flag",
      correct: "BLACKOUT{threat_contained}",
      points: 20,
      hint: "Name LAB-PC-05, the suspicious user, a key IOC, and what to isolate first.",
      requires: ["F1", "F2", "F3", "F4", "F5"],
    },
  ],
  finalReport: {
    correctHost: "LAB-PC-05",
    hostOptions: ["LAB-PC-01", "LAB-PC-05", "SERVER-02", "ADMIN-PC", "UTC-WEB-03"],
    userKeywords: ["j.mensah", "mensah", "admin-remote", "03:14", "accra", "lagos", "impossible", "travel"],
    iocKeywords: [
      "185.243.112.44",
      "185.243",
      "update-cdn.novatech-secure.net",
      "novatech-secure",
      "a3f1c9e2",
      "hash",
      "ioc",
      "c2",
      "beacon",
    ],
    isolateKeywords: [
      "lab-pc-05",
      "lab pc 05",
      "isolate",
      "quarantine",
      "disconnect",
      "contain",
      "block",
      "segment",
      "185.243",
      "c2",
      "endpoint",
    ],
  },
  skills: [
    "How threat hunters investigate attackers",
    "How to recognize Indicators of Compromise (IOCs)",
    "How firewall logs reveal attacker behaviour",
    "Why endpoint monitoring matters",
    "How to prioritize systems during an active incident",
  ],
  badge: "Threat Hunter I",
  maxHints: 6,
  hintPenalty: 5,
  bonusNoHints: 10,
  bonusFastMinutes: 75,
  bonusFastPoints: 10,
};
