export const MISSION_004 = {
  id: "M04",
  caseNumber: "ACC-004",
  title: "THE BREACHED VAULT",
  shortTitle: "MISSION 004",
  category: "Authentication & Password Security",
  difficulty: "Intermediate",
  points: 100,
  timeLimitSec: 75 * 60,
  startLabel: "Access Authentication Server",
  caseFile: {
    heading: "CASE FILE ACC-004",
    intro:
      "A university database has been breached. Investigators recovered fragments of the authentication server before it crashed. The attackers did not exploit advanced hacking techniques. Instead, they took advantage of weak passwords and poor security practices. Your mission is to investigate the evidence, identify the security weaknesses, recover hidden flags, and recommend how the breach could have been prevented.",
  },
  objectives: [
    "Inspect authentication logs",
    "Identify weak passwords",
    "Understand password hashing",
    "Detect authentication failures",
    "Recover all hidden flags",
  ],
  evidence: [
    {
      id: "E001",
      title: "Login Records",
      type: "logs",
      description: "Recovered authentication history from the campus auth gateway.",
    },
    {
      id: "E002",
      title: "Password Vault",
      type: "vault",
      description: "Sample credentials recovered from the breached credential store.",
    },
    {
      id: "E003",
      title: "Hash Laboratory",
      type: "hashes",
      description: "Compare plaintext passwords with stored hash fragments.",
    },
    {
      id: "E004",
      title: "Security Policy",
      type: "policy",
      description: "Official university password policy vs. what users actually chose.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "Login records flag",
      correct: "ACC{login_detective}",
      points: 20,
      hint: "Scan every login line carefully — one failed attempt hides more than a username.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "Strong password flag",
      correct: "ACC{strong_password}",
      points: 20,
      hint: "Mark weak vs strong passwords. The long passphrase is the only truly strong entry.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "Hash match flag",
      correct: "ACC{hash_master}",
      points: 20,
      hint: "Match each hash fragment to its plaintext. Complete all correct pairs to reveal the flag.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "Policy review flag",
      correct: "ACC{policy_guardian}",
      points: 20,
      hint: "Read the full policy document — the final evidence is embedded in one paragraph.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "Vault secured flag",
      correct: "ACC{vault_secured}",
      points: 20,
      hint: "Name the mistakes that enabled the breach and recommend at least three concrete improvements.",
      requires: ["F1", "F2", "F3", "F4"],
    },
  ],
  finalAssessment: {
    mistakesKeywords: [
      "weak",
      "password",
      "reuse",
      "policy",
      "bruteforce",
      "brute",
      "mfa",
      "2fa",
      "hash",
      "plain",
      "default",
      "admin",
      "dictionary",
      "spray",
      "lockout",
      "monitor",
    ],
    improveKeywords: [
      "mfa",
      "2fa",
      "multi-factor",
      "multifactor",
      "length",
      "passphrase",
      "manager",
      "hash",
      "bcrypt",
      "argon",
      "lockout",
      "rate",
      "monitor",
      "audit",
      "policy",
      "educat",
      "phish",
      "unique",
      "complex",
      "salt",
    ],
  },
  skills: [
    "Why weak passwords are dangerous",
    "How password hashing protects users",
    "Why password policies matter",
    "How attackers exploit poor authentication",
    "Best practices for securing online accounts",
  ],
  badge: "Authentication Analyst I",
  maxHints: 5,
  hintPenalty: 5,
  bonusNoHints: 10,
  bonusFastMinutes: 60,
  bonusFastPoints: 10,
};
