export const MISSION_003 = {
  id: "M03",
  caseNumber: "ACC-003",
  title: "THE NETWORK INTRUDER",
  shortTitle: "MISSION 003",
  category: "Networking & Network Investigation",
  difficulty: "Intermediate",
  points: 100,
  timeLimitSec: 75 * 60,
  caseFile: {
    heading: "CASE FILE ACC-003",
    intro:
      "At exactly 2:14 AM, the University Network Monitoring System detected an unknown device communicating with several campus computers. The attacker disappeared before security personnel could respond. Only the network logs were recovered. Your job is to investigate the evidence, identify the attacker, trace their activity, and stop the intrusion. Every clue matters.",
  },
  objectives: [
    "Inspect recovered network evidence",
    "Identify suspicious devices",
    "Trace attacker activity",
    "Recover all hidden flags",
    "Complete the investigation report",
  ],
  evidence: [
    {
      id: "E001",
      title: "Campus Network Map",
      type: "map",
      description: "Interactive topology of the campus LAN at the time of the alert.",
    },
    {
      id: "E002",
      title: "Recovered Network Log",
      type: "logs",
      description: "Packet and session logs from the monitoring appliance.",
    },
    {
      id: "E003",
      title: "Device Information",
      type: "devices",
      description: "Asset inventory snapshot for connected endpoints.",
    },
    {
      id: "E004",
      title: "Recovered Chat Conversation",
      type: "chat",
      description: "Internal SOC channel discussing the 02:14 AM alert.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "Network map flag",
      correct: "ACC{network_mapper}",
      points: 20,
      hint: "Click every node on the map — one device is not part of the official inventory.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "Network log flag",
      correct: "ACC{log_hunter}",
      points: 20,
      hint: "Scroll the log carefully. One line hides more than a timestamp.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "Suspicious device flag",
      correct: "ACC{device_found}",
      points: 20,
      hint: "Compare MAC and status fields — the intruder will not look like a normal campus asset.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "SOC chat flag",
      correct: "ACC{soc_detective}",
      points: 20,
      hint: "Read every message in the team chat. Someone pasted a clue casually.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "Investigation completion flag",
      correct: "ACC{intruder_stopped}",
      points: 20,
      hint: "Name the unknown device, explain why it is suspicious, and isolate it from the network.",
      requires: ["F1", "F2", "F3", "F4"],
    },
  ],
  finalReport: {
    deviceOptions: [
      "UMaT-Core-Router",
      "LAB-SWITCH-01",
      "FILE-SERVER-A",
      "STAFF-PC-14",
      "Unknown Device (192.168.1.88)",
      "Student-PC-07",
    ],
    correctDevice: "Unknown Device (192.168.1.88)",
    whyKeywords: ["unknown", "unauthorized", "mac", "2:14", "0214", "not registered", "suspicious", "rogue", "attacker", "intruder"],
    actionKeywords: ["isolate", "block", "disconnect", "disable", "quarantine", "revoke", "firewall", "contain", "kick", "remove"],
  },
  skills: [
    "How a network is structured",
    "How to inspect network logs",
    "How to identify suspicious devices",
    "How attackers move through networks",
    "How Security Operations Centers investigate incidents",
  ],
  badge: "Network Analyst I",
  maxHints: 5,
  hintPenalty: 5,
  bonusNoHints: 10,
  bonusFastMinutes: 60,
  bonusFastPoints: 10,
};
