export const MISSION_006 = {
  id: "M06",
  caseNumber: "ACC-006",
  title: "OPERATION BLACKOUT – PART I",
  shortTitle: "MISSION 006",
  subtitle: "THE BREACH",
  category: "Incident Response & Digital Investigation",
  difficulty: "Advanced",
  points: 100,
  timeLimitSec: 90 * 60,
  startLabel: "ENTER INCIDENT RESPONSE ROOM",
  series: {
    name: "Operation Blackout",
    part: 1,
    of: 5,
  },
  caseFile: {
    heading: "PRIORITY ALERT",
    intro:
      "CLASSIFICATION: CONFIDENTIAL. TIME: 07:42 GMT. A major cyber incident has struck the University Technology Centre. Several servers suddenly went offline. Student records cannot be accessed. Internet connectivity across multiple departments has been disrupted. Your response team has been deployed. Your first objective is simple: Understand what happened. Collect evidence. Prepare for the investigation.",
  },
  objectives: [
    "Examine the incident",
    "Identify affected systems",
    "Build the attack timeline",
    "Recover every hidden flag",
    "Prepare the response team",
  ],
  evidence: [
    {
      id: "E001",
      title: "Incident Dashboard",
      type: "dashboard",
      description: "Critical alerts, offline servers, and live security notifications.",
    },
    {
      id: "E002",
      title: "Server Status",
      type: "servers",
      description: "Health board for core university technology services.",
    },
    {
      id: "E003",
      title: "System Logs",
      type: "logs",
      description: "Recovered host and authentication events around 07:39–07:43.",
    },
    {
      id: "E004",
      title: "Emergency Email",
      type: "email",
      description: "Priority message from the ICT Director to ACRT.",
    },
    {
      id: "E005",
      title: "Incident Timeline Board",
      type: "timeline",
      description: "Ordered event cards reconstructing the first minutes of the breach.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "Incident dashboard flag",
      correct: "ACC{incident_detected}",
      points: 20,
      hint: "Open every critical alert on the dashboard — one notification embeds the case token.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "Server status flag",
      correct: "ACC{server_down}",
      points: 20,
      hint: "Inspect offline nodes carefully. One downed server card carries residual evidence.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "System logs flag",
      correct: "ACC{log_recovered}",
      points: 20,
      hint: "Scroll the 07:39–07:43 window. One recovered line is more than a timestamp.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "Emergency email flag",
      correct: "ACC{email_priority}",
      points: 20,
      hint: "Read the ICT Director’s entire message — a priority sentence hides the token.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "Timeline board flag",
      correct: "ACC{timeline_started}",
      points: 20,
      hint: "Open each timeline card. The earliest confirmed event holds the flag.",
      evidenceId: "E005",
    },
    {
      id: "F6",
      task: 6,
      label: "Incident confirmed flag",
      correct: "ACC{incident_confirmed}",
      points: 20,
      hint: "Name affected systems, the first event, priority evidence, and immediate response actions.",
      requires: ["F1", "F2", "F3", "F4", "F5"],
    },
  ],
  finalReport: {
    systemsKeywords: [
      "database",
      "auth",
      "authentication",
      "web",
      "mail",
      "dns",
      "server",
      "student",
      "record",
      "network",
      "internet",
    ],
    firstKeywords: [
      "07:39",
      "0739",
      "login",
      "first",
      "auth",
      "failed",
      "before",
      "earliest",
      "user login",
    ],
    evidenceKeywords: [
      "log",
      "timeline",
      "alert",
      "dashboard",
      "server",
      "email",
      "process",
      "database",
    ],
    actionKeywords: [
      "isolat",
      "contain",
      "preserve",
      "evidence",
      "log",
      "snapshot",
      "notify",
      "incident",
      "triage",
      "disable",
      "block",
      "monitor",
      "escalate",
      "backup",
      "team",
    ],
  },
  skills: [
    "How incident response begins",
    "Why logs are critical",
    "How to prioritize evidence",
    "How cyber teams assess attacks",
    "Why the first hour of an incident is important",
  ],
  badge: "Incident Responder I",
  maxHints: 6,
  hintPenalty: 5,
  bonusNoHints: 10,
  bonusFastMinutes: 75,
  bonusFastPoints: 10,
};
