export const MISSION_005 = {
  id: "M05",
  caseNumber: "ACC-005",
  title: "THE HIDDEN WEBSITE",
  shortTitle: "MISSION 005",
  category: "Web Security & Client-Side Investigation",
  difficulty: "Intermediate",
  points: 100,
  timeLimitSec: 90 * 60,
  startLabel: "Launch Website Investigation",
  caseFile: {
    heading: "CASE FILE ACC-005",
    intro:
      "A local technology company has reported unusual activity on its website. Customers claim they discovered pages that should not be publicly accessible. The web server appears normal, but investigators believe hidden clues remain inside the website. Your mission is to inspect every part of the website, recover the hidden evidence, and identify security weaknesses before attackers do.",
  },
  objectives: [
    "Inspect a suspicious website",
    "Explore hidden pages",
    "Read HTML source",
    "Investigate JavaScript",
    "Recover all hidden flags",
  ],
  evidence: [
    {
      id: "E001",
      title: "HTML Source",
      type: "html",
      description: "Inspect page markup — comments can hide more than developers intend.",
    },
    {
      id: "E002",
      title: "JavaScript File",
      type: "js",
      description: "Review client-side scripts linked from the company site.",
    },
    {
      id: "E003",
      title: "Hidden Page",
      type: "hidden",
      description: "An unlinked path still served by the web host.",
    },
    {
      id: "E004",
      title: "Image Investigation",
      type: "image",
      description: "Filenames, alt text, and captions can leak sensitive clues.",
    },
  ],
  flags: [
    {
      id: "F1",
      task: 1,
      label: "HTML source flag",
      correct: "ACC{view_source_master}",
      points: 20,
      hint: "Open View Source on the company site — look inside HTML comments on the Home page.",
      evidenceId: "E001",
    },
    {
      id: "F2",
      task: 2,
      label: "JavaScript flag",
      correct: "ACC{js_investigator}",
      points: 20,
      hint: "Open site.js from the toolkit or source viewer. Secrets hide in comments and variables.",
      evidenceId: "E002",
    },
    {
      id: "F3",
      task: 3,
      label: "Hidden page flag",
      correct: "ACC{hidden_directory}",
      points: 20,
      hint: "Clues on About and in robots.txt mention /backup — visit that unlinked path.",
      evidenceId: "E003",
    },
    {
      id: "F4",
      task: 4,
      label: "Image investigation flag",
      correct: "ACC{image_detective}",
      points: 20,
      hint: "Inspect every image — one filename or alt attribute is not marketing copy.",
      evidenceId: "E004",
    },
    {
      id: "F5",
      task: 5,
      label: "Website secured flag",
      correct: "ACC{website_secured}",
      points: 20,
      hint: "List at least three mistakes (comments, JS secrets, hidden pages, image metadata) and recommend fixes.",
      requires: ["F1", "F2", "F3", "F4"],
    },
  ],
  finalAssessment: {
    mistakesKeywords: [
      "comment",
      "html",
      "javascript",
      "js",
      "secret",
      "hidden",
      "backup",
      "admin",
      "image",
      "alt",
      "filename",
      "source",
      "robots",
      "expos",
      "leak",
      "sensitive",
      "unlinked",
      "directory",
    ],
    improveKeywords: [
      "remov",
      "comment",
      "secret",
      "env",
      "server",
      "auth",
      "restrict",
      "block",
      "robots",
      "review",
      "audit",
      "scan",
      "metadata",
      "alt",
      "deploy",
      "access",
      "permission",
      "sanitize",
      "minify",
      "ci",
    ],
  },
  skills: [
    "Websites reveal hidden information.",
    "HTML comments should never contain sensitive data.",
    "JavaScript files can expose secrets.",
    "Hidden pages can become security risks.",
    "Small website mistakes can lead to bigger security issues.",
  ],
  badge: "Web Investigator I",
  maxHints: 5,
  hintPenalty: 5,
  bonusNoHints: 10,
  bonusFastMinutes: 75,
  bonusFastPoints: 10,
};
